#!/usr/bin/env ruby

# frozen_string_literal: true

require 'pry'

lib_path = File.expand_path(File.join(File.dirname(__FILE__), '../lib'))
gem_path = File.expand_path(File.join(File.dirname(__FILE__), '../Gemfile'))

$LOAD_PATH.unshift(lib_path)

ENV['BUNDLE_GEMFILE'] = gem_path

require 'bundler/setup'
require 'k_manager'
require 'k_manager/cli/commands'

Dry::CLI.new(KManager::Cli::Commands).call
